# Generated by Django 5.2.10 on 2026-01-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
