# Generated by Django 5.2 on 2026-05-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_caps_conversation_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='smiles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('cap', 'Cap'), ('smile', 'Smile')], max_length=10),
        ),
    ]
