# Generated by Django 5.2 on 2026-05-14 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_smiles_alter_messagereaction_reaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chat.messagecomment'),
        ),
    ]
