# Generated by Django 5.2 on 2026-05-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_messagecomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagecomment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
