# Generated by Django 5.2.10 on 2026-09-27 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_conversation_is_removed_message_is_removed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sponsorshiprequest',
            name='user1_accepted',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorshiprequest',
            name='user2_accepted',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
