# Generated by Django 5.2.10 on 2026-10-05 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_conversationbookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('normalized_text', models.TextField(db_index=True)),
                ('semantic_terms', models.TextField(blank=True)),
                ('message_timestamp', models.DateTimeField(db_index=True)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_documents', to='chat.conversation')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_document', to='chat.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['conversation', '-message_timestamp'], name='chat_search_convers_a91ddc_idx'), models.Index(fields=['sender', '-message_timestamp'], name='chat_search_sender__6114ed_idx')],
            },
        ),
    ]
